version: "3"

services:
  httpd:
    build: ./apache-php-mysqli
    container_name: httpd
    ports:
      - "3080:80"
    volumes:
      - ../htdocs:/var/www/html

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 3278
    ports:
      - "3060:3306"
    volumes:
      - ../mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: mariadb
    ports:
      - "3050:80"
